services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_DB=pg_play
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
